### ISSUE TITLE
Bokeh Error Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by permissionx** [arosen93/ptable_trends#3]
python 3.5.1
bokeh.__version__       0.12.10

I just did as README.md says, but it turned out that "Cannot read property 'value' of undefined" in the browser.
![_20171119192911](https://user-images.githubusercontent.com/12381936/32990297-00484b62-cd62-11e7-9586-43d2f1573a4e.png)

**Comment by arosen93** [comment]
Thanks for reporting this issue. It seems to be related to a change in the newer version of bokeh. I'll track that down (the error is incredibly vague...).

**Comment by arosen93** [comment]
Should be all fixed!

**Comment by arosen93** [comment]
There we go! Now it should be good. Let me know if you run into any other issues.

**Comment by permissionx** [comment]
Thank you!
