### ISSUE TITLE
Great plotting tool.

### ISSUE THREAD

**Issue by jdagdelen** [arosen93/ptable_trends#7]
Would be even better if there was a simple function that you could call from python rather than the command line.

**Comment by arosen93** [comment]
100% agreed. The joys of revisiting things you wrote 3-4 years ago... 

Will take care of that when I have a spare moment, which unfortunately won't be for a bit. Thanks for the reminder about this.

**Comment by jdagdelen** [comment]
Ah, probably not necessary. I forgot the golden rule of working in computational materials: "Check if pymatgen does it" 

https://pymatgen.org/pymatgen.util.plotting.html#pymatgen.util.plotting.periodic_table_heatmap

**Comment by arosen93** [comment]
Ha! The golden rule. I love it. Thanks for sharing that Pymatgen feature!

**Comment by arosen93** [comment]
Surprised I needed this again and decided to clean up this mess a little bit. Closed in [c6e416f](https://github.com/arosen93/ptable_trends/commit/c6e416fb05aefb16bc7b307ba814e5f6eef745d7).
